from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, JSON, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..db import Base


class Signal(Base):
    """
    Follow-trade signal generated by the strategy engine.
    """

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow, nullable=False, index=True
    )

    symbol: Mapped[str] = mapped_column(String(64), nullable=False)
    side: Mapped[str] = mapped_column(String(8), nullable=False)  # 'long' / 'short'

    price_range_min: Mapped[float] = mapped_column(Float, nullable=False)
    price_range_max: Mapped[float] = mapped_column(Float, nullable=False)

    smart_trader_count: Mapped[int] = mapped_column(Integer, nullable=False)
    trader_addresses: Mapped[list[str]] = mapped_column(JSON, nullable=False)

    signal_strength: Mapped[float | None] = mapped_column(Float, nullable=True)

    executed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    executed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    follower_trades: Mapped[list["FollowerTrade"]] = relationship(
        "FollowerTrade",
        back_populates="signal",
        cascade="all, delete-orphan",
    )

